# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-27 02:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='project_holder',
            new_name='project_lead',
        ),
    ]
